//! Pure Rust local RAG (Retrieval-Augmented Generation) client library using an in-memory
//! vector array and Ollama for embeddings.
//!
//! This library provides functionality for:
//! - Parsing PDF documents and extracting text
//! - Generating embeddings via Ollama's batch embedding API
//! - Persisting embeddings to JSON for incremental updates
//! - Detecting changed or deleted PDF files
//! - Computing document similarity via dot product
//!
//! # Example
//!
//! ```ignore
//! use ragrig::{generate_all_embeddings, Args};
//!
//! let args = Args {
//!     folder: std::path::PathBuf::from("./documents"),
//!     model: "erwan2/DeepSeek-R1-Distill-Qwen-14B:latest".to_string(),
//!     embedding_model: "nomic-embed-text".to_string(),
//!     threads: 4,
//!     embedding_concurrency: 32,
//!     batch_size: 128,
//! };
//!
//! let http_client = reqwest::Client::new();
//! let embeddings = generate_all_embeddings(
//!     &args,
//!     &http_client,
//!     "http://localhost:11434/api/embed",
//! ).await?;
//! ```

use anyhow::{Result, anyhow};
use clap::Parser;
use rayon::prelude::*;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fs;
use std::io::Read;
use std::panic::catch_unwind;
use std::path::{Path, PathBuf};
use std::time::SystemTime;
use walkdir::WalkDir;

// --- Document Types ---

/// Represents a document file type for indexing.
///
/// Supports both PDF and EPUB formats. Each variant wraps a `PathBuf` pointing to the
/// actual file on disk. This enum is used throughout the library to distinguish between
/// different document types during parsing and embedding generation.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum DocumentType {
    /// A PDF document file
    Pdf(PathBuf),
    /// An EPUB document file
    Epub(PathBuf),
}

// --- File Hash Entry ---

/// Represents a file's name and its SHA-256 hash for change detection.
///
/// This struct is used to track which document files have been indexed and to detect
/// when files have been modified or replaced by comparing hash values.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FileHashEntry {
    /// The name of the file (e.g., "document.pdf" or "book.epub")
    pub file_name: String,
    /// The SHA-256 hash of the file's contents
    pub hash: String,
}

// --- Shared Data Contracts ---

/// A chunk of text extracted from a PDF document along with its embedding vector.
///
/// Each `DocumentChunk` represents a segment of text (approximately 500 characters)
/// extracted from a source PDF file, along with its corresponding embedding vector
/// generated by Ollama. This is the primary data structure used for document retrieval
/// in the RAG system.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DocumentChunk {
    /// The original text content of this chunk
    pub text: String,
    /// The embedding vector (generated by Ollama)
    pub vector: Vec<f32>,
    /// The name of the source PDF file this chunk was extracted from
    pub source_file: String,
}

/// Persistent storage format for embeddings database.
///
/// This struct represents the complete state of the embedding database, including all
/// document chunks, their associated file hashes (for change detection), and a creation
/// timestamp. It is serialized to JSON and stored on disk to enable incremental updates
/// without re-indexing all documents.
#[derive(Serialize, Deserialize)]
pub struct EmbeddingsDatabase {
    /// All document chunks with their embedding vectors
    pub chunks: Vec<DocumentChunk>,
    /// Hash entries for all indexed files (used to detect changes)
    pub file_hashes: Vec<FileHashEntry>,
    /// Unix timestamp (seconds) when this database was created
    pub created_at: i64,
}

/// Batch embedding request structure matching Ollama's /api/embed endpoint
#[derive(Serialize)]
pub struct BatchEmbeddingRequest {
    pub model: String,
    pub input: Vec<String>,
}

/// Batch embedding response structure from Ollama's /api/embed endpoint
#[derive(Deserialize)]
pub struct BatchEmbeddingResponse {
    pub embeddings: Vec<Vec<f32>>,
}

/// Request structure for Ollama's chat/generation endpoint.
///
/// Used to send prompts to a language model via Ollama's API for text generation.
#[derive(Serialize)]
pub struct ChatRequest {
    /// The name of the model to use for generation
    pub model: String,
    /// The prompt text to send to the model
    pub prompt: String,
    /// Whether to stream the response (currently unused)
    pub stream: bool,
}

/// Response chunk from Ollama's chat/generation endpoint.
///
/// Represents a single chunk of a streamed response from Ollama's API. Each chunk
/// contains a portion of the generated text and a flag indicating whether generation
/// is complete.
#[derive(Deserialize)]
pub struct ChatResponseChunk {
    /// The text content of this response chunk
    pub response: Option<String>,
    /// Whether the generation is complete (`true`) or more chunks are expected (`false`)
    pub done: bool,
}

// --- CLI Setup ---

#[derive(Parser, Debug)]
#[command(about = "Pure Rust local RAG client using an in-memory vector array and Ollama")]
pub struct Args {
    /// Path to the folder containing your baseline PDF documents
    #[arg(short, long)]
    pub folder: PathBuf,

    /// LLM to use for generation
    #[arg(
        short,
        long,
        default_value = "erwan2/DeepSeek-R1-Distill-Qwen-14B:latest"
    )]
    pub model: String,

    /// Model to use for generating embeddings
    #[arg(short, long, default_value = "nomic-embed-text")]
    pub embedding_model: String,

    /// Number of worker threads for PDF parsing (CPU-bound)
    #[arg(short, long, default_value = "4")]
    pub threads: usize,

    /// Number of concurrent embedding requests to Ollama (I/O-bound, can be much higher than threads)
    #[arg(long, default_value = "32")]
    pub embedding_concurrency: usize,

    /// Batch size for batch embedding requests (128 is optimal for most GPUs)
    #[arg(long, default_value = "128")]
    pub batch_size: usize,
}

// --- Core Helper Functions ---

/// Generates a vector embedding for a single text input via the local Ollama API.
///
/// Sends the text to Ollama's `/api/embed` endpoint and returns the resulting embedding vector.
/// This function wraps the text in a `BatchEmbeddingRequest` internally.
///
/// # Arguments
///
/// * `client` - A configured `reqwest::Client` for making HTTP requests
/// * `url` - The Ollama API URL (e.g., `"http://localhost:11434/api/embed"`)
/// * `model` - The name of the embedding model to use (e.g., `"nomic-embed-text"`)
/// * `text` - The text to generate an embedding for
///
/// # Returns
///
/// A `Vec<f32>` containing the embedding vector on success.
///
/// # Errors
///
/// Returns an error if:
/// - The HTTP request fails
/// - Ollama returns a non-success status code
/// - The response cannot be parsed
/// - The embeddings array is empty in the response
pub async fn get_embedding(
    client: &reqwest::Client,
    url: &str,
    model: &str,
    text: &str,
) -> Result<Vec<f32>> {
    let payload = BatchEmbeddingRequest {
        model: model.to_string(),
        input: vec![text.to_string()],
    };
    let res = client.post(url).json(&payload).send().await?;
    let status = res.status();
    let body_text = res.text().await?;

    if !status.is_success() {
        return Err(anyhow!("Ollama API error ({}): {}", status, body_text));
    }

    match serde_json::from_str::<BatchEmbeddingResponse>(&body_text) {
        Ok(body) => {
            if body.embeddings.is_empty() {
                return Err(anyhow!("Embeddings array is empty in response"));
            }
            Ok(body.embeddings[0].clone())
        }
        Err(e) => Err(anyhow!(
            "Failed to parse embedding response: {}\nResponse was: {}",
            e,
            body_text
        )),
    }
}

/// Calculates the dot product similarity between two vectors.
///
/// The dot product is computed as: `Σ(v1[i] * v2[i])` for all indices `i`.
/// This is a fast, CPU-based similarity measure useful for comparing embedding vectors
/// in a local RAG system without requiring external computation.
///
/// # Arguments
///
/// * `v1` - First vector
/// * `v2` - Second vector
///
/// # Returns
///
/// The dot product sum of the two vectors. Higher values indicate greater similarity.
///
/// # Panics
///
/// This function does not panic. If the vectors have different lengths, the shorter
/// vector's elements are used (extra elements in the longer vector are ignored).
pub fn dot_product(v1: &[f32], v2: &[f32]) -> f32 {
    v1.iter().zip(v2.iter()).map(|(x, y)| x * y).sum()
}

// --- Embedding Persistence Functions ---

/// Returns the default path for storing embeddings within a given folder.
///
/// The embeddings are stored in a hidden file named `.ragrig_embeddings.json` inside
/// the specified folder.
///
/// # Arguments
///
/// * `folder` - The folder path where the embeddings file should be located
///
/// # Returns
///
/// A `PathBuf` pointing to the embeddings file (e.g., `/path/to/folder/.ragrig_embeddings.json`)
pub fn get_embeddings_file_path(folder: &Path) -> PathBuf {
    folder.join(".ragrig_embeddings.json")
}

/// Computes SHA-256 hash of a file's contents
pub fn compute_file_hash(path: &Path) -> Result<String> {
    let mut file = fs::File::open(path)?;
    let mut hasher = Sha256::new();
    let mut buffer = [0u8; 8192];

    loop {
        let bytes_read = file.read(&mut buffer)?;
        if bytes_read == 0 {
            break;
        }
        hasher.update(&buffer[..bytes_read]);
    }

    let result = hasher.finalize();
    Ok(format!("{:x}", result))
}

/// Collects all document files (PDF and EPUB) in a folder with their SHA-256 hashes
pub fn get_document_file_hashes(folder: &Path) -> Result<Vec<(DocumentType, String)>> {
    let mut document_files = Vec::new();

    for entry in WalkDir::new(folder).into_iter().filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.is_file() {
            if let Some(ext) = path.extension().and_then(|s| s.to_str()) {
                let doc_type = match ext {
                    "pdf" => DocumentType::Pdf(path.to_path_buf()),
                    "epub" => DocumentType::Epub(path.to_path_buf()),
                    _ => continue,
                };
                if let Ok(hash) = compute_file_hash(path) {
                    document_files.push((doc_type, hash));
                }
            }
        }
    }

    Ok(document_files)
}

/// Finds documents (PDF or EPUB) that are new or have been modified based on hash comparison
pub fn get_changed_documents(
    current_files: &[(DocumentType, String)],
    stored_hashes: &[FileHashEntry],
) -> Vec<(DocumentType, String)> {
    // Create a map of stored hashes for quick lookup
    let stored_map: std::collections::HashMap<&str, &str> = stored_hashes
        .iter()
        .map(|entry| (entry.file_name.as_str(), entry.hash.as_str()))
        .collect();

    // Find files that are new or have changed hash
    let mut changed_files = Vec::new();
    for (doc_type, current_hash) in current_files {
        let file_name = match doc_type {
            DocumentType::Pdf(path) => path.file_name().unwrap().to_string_lossy().into_owned(),
            DocumentType::Epub(path) => path.file_name().unwrap().to_string_lossy().into_owned(),
        };
        match stored_map.get(file_name.as_str()) {
            Some(stored_hash) => {
                if stored_hash != current_hash {
                    changed_files.push((doc_type.clone(), file_name));
                }
            }
            None => {
                // New file not in stored hashes
                changed_files.push((doc_type.clone(), file_name));
            }
        }
    }

    changed_files
}

/// Removes embeddings for files that no longer exist in the folder
pub fn remove_deleted_embeddings(
    vector_db: &mut Vec<DocumentChunk>,
    current_files: &[(DocumentType, String)],
) {
    // Create a set of current file names
    let current_file_names: std::collections::HashSet<String> = current_files
        .iter()
        .map(|(doc_type, _)| match doc_type {
            DocumentType::Pdf(path) => path.file_name().unwrap().to_string_lossy().into_owned(),
            DocumentType::Epub(path) => path.file_name().unwrap().to_string_lossy().into_owned(),
        })
        .collect();

    // Remove chunks from deleted files
    vector_db.retain(|chunk| current_file_names.contains(&chunk.source_file));
}

/// Saves embeddings and file hashes to a JSON file for persistence.
///
/// Creates or overwrites the file at the given path with a serialized `EmbeddingsDatabase`
/// containing all document chunks, their file hashes, and a creation timestamp. This enables
/// incremental updates by storing the current state of indexed documents.
///
/// # Arguments
///
/// * `path` - The file path where embeddings will be saved
/// * `embeddings` - Slice of `DocumentChunk` entries to persist
/// * `file_hashes` - Slice of `(DocumentType, String)` tuples representing indexed documents and their hashes
///
/// # Errors
///
/// Returns an error if:
/// - The file cannot be written to disk
/// - JSON serialization fails
/// - The current timestamp cannot be obtained
pub fn save_embeddings(
    path: &Path,
    embeddings: &[DocumentChunk],
    file_hashes: &[(DocumentType, String)],
) -> Result<()> {
    // Convert current file hashes to FileHashEntry format
    let hash_entries: Vec<FileHashEntry> = file_hashes
        .iter()
        .map(|(doc_type, hash)| {
            let file_name = match doc_type {
                DocumentType::Pdf(path) => path.file_name().unwrap().to_string_lossy().into_owned(),
                DocumentType::Epub(path) => {
                    path.file_name().unwrap().to_string_lossy().into_owned()
                }
            };
            FileHashEntry {
                file_name,
                hash: hash.clone(),
            }
        })
        .collect();

    let db = EmbeddingsDatabase {
        chunks: embeddings.to_vec(),
        file_hashes: hash_entries,
        created_at: SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)?
            .as_secs() as i64,
    };
    let json = serde_json::to_string(&db)?;
    fs::write(path, json)?;
    println!("Embeddings saved to: {}", path.display());
    Ok(())
}

/// Loads embeddings and file hashes from a previously saved JSON file.
///
/// Deserializes the `EmbeddingsDatabase` from the file at the given path and returns
/// a tuple containing the document chunks and file hashes.
///
/// # Arguments
///
/// * `path` - The file path to load embeddings from
///
/// # Returns
///
/// A tuple `(Vec<DocumentChunk>, Vec<FileHashEntry>)` containing:
/// - All document chunks with their embedding vectors
/// - File hash entries for change detection
///
/// # Errors
///
/// Returns an error if:
/// - The file does not exist or cannot be read
/// - The JSON is malformed or cannot be deserialized
pub fn load_embeddings(path: &Path) -> Result<(Vec<DocumentChunk>, Vec<FileHashEntry>)> {
    let json = fs::read_to_string(path)?;
    let db: EmbeddingsDatabase = serde_json::from_str(&json)?;
    Ok((db.chunks, db.file_hashes))
}

/// Generates embeddings for a list of document files (PDF or EPUB) by parsing text, chunking, and calling Ollama's batch embedding API.
///
/// This is the core function for embedding generation. It:
/// 1. Parses each document (PDF or EPUB) in parallel using `rayon`
/// 2. Extracts text and splits it into ~500 character chunks
/// 3. Sends chunks to Ollama in batches for vectorization
/// 4. Returns all document chunks with their embedding vectors
///
/// Document parsing failures are handled gracefully - failed files are skipped with error messages.
/// Embedding request failures are also handled gracefully with warning messages.
///
/// # Arguments
///
/// * `args` - CLI arguments containing the embedding model and batch size
/// * `http_client` - A configured `reqwest::Client` for making HTTP requests
/// * `embed_url` - The Ollama batch embedding API URL (e.g., `"http://localhost:11434/api/embed"`)
/// * `document_files` - Vector of `(DocumentType, String)` tuples containing file paths and names
///
/// # Returns
///
/// A `Vec<DocumentChunk>` containing all successfully embedded text chunks with their vectors.
///
/// # Examples
///
/// ```ignore
/// let args = Args::parse();
/// let client = reqwest::Client::new();
/// let pdf_files = vec![(DocumentType::Pdf(PathBuf::from("doc.pdf")), "doc.pdf".to_string())];
/// let chunks = generate_embeddings_for_documents(
///     &args,
///     &client,
///     "http://localhost:11434/api/embed",
///     pdf_files,
/// ).await?;
/// ```
pub async fn generate_embeddings_for_documents(
    args: &Args,
    http_client: &reqwest::Client,
    embed_url: &str,
    document_files: Vec<(DocumentType, String)>,
) -> Result<Vec<DocumentChunk>> {
    println!("Parsing {} documents in parallel...", document_files.len());

    // Parse documents in parallel using rayon
    let parsed_chunks: Vec<(String, Vec<String>)> = document_files
        .into_par_iter()
        .filter_map(|(doc_type, file_name)| {
            println!("Parsing document: {}", file_name);

            let raw_text = match &doc_type {
                DocumentType::Pdf(path) => {
                    let extraction_result = catch_unwind(|| pdf_extract::extract_text(path));
                    match extraction_result {
                        Ok(Ok(text)) => Some(text),
                        Ok(Err(_)) => {
                            eprintln!("  -> Failed to extract text from PDF (extraction error)");
                            None
                        }
                        Err(_) => {
                            eprintln!(
                                "  -> Failed to extract text from PDF (parser encountered unsupported feature)"
                            );
                            None
                        }
                    }
                }
                DocumentType::Epub(path) => {
                    let extraction_result = catch_unwind(|| {
                        let book = epub_parser::Epub::parse(path)?;
                        let mut text = String::new();
                        for page in &book.pages {
                            text.push_str(&page.content.replace(['\n', '\r'], " "));
                        }
                        anyhow::Ok(text)
                    });
                    match extraction_result {
                        Ok(Ok(text)) => Some(text),
                        Ok(Err(e)) => {
                            eprintln!("  -> Failed to extract text from EPUB: {}", e);
                            None
                        }
                        Err(_) => {
                            eprintln!("  -> Failed to extract text from EPUB (parser encountered unsupported feature)");
                            None
                        }
                    }
                }
            };

            raw_text.map(|text| {
                // Sliding window chunking (approx 500 character slices)
                let chunks: Vec<String> = text
                    .chars()
                    .collect::<Vec<char>>()
                    .chunks(500)
                    .map(|c| c.iter().collect::<String>())
                    .collect();
                (file_name, chunks)
            })
        })
        .collect();

    println!(
        "Extracted {} total text blocks. Commencing GPU Batch Vectorization...",
        parsed_chunks
            .iter()
            .map(|(_, chunks)| chunks.len())
            .sum::<usize>()
    );

    // Collect all chunks with their source file metadata
    let mut all_chunks: Vec<(String, String)> = Vec::new(); // (text, source_file)
    for (file_name, chunks) in parsed_chunks {
        let chunks_count = chunks.len();
        println!("  -> {} has {} text segments", file_name, chunks_count);

        for chunk in chunks {
            if chunk.trim().is_empty() {
                continue;
            }
            all_chunks.push((chunk, file_name.clone()));
        }
    }

    println!(
        "Generating embeddings for {} total text segments using batch endpoint...",
        all_chunks.len()
    );

    // Process chunks in batches for optimal GPU utilization
    let batch_size = args.batch_size;
    let mut vector_db: Vec<DocumentChunk> = Vec::new();
    let mut successful_embeddings = 0;
    let mut failed_embeddings = 0;

    for batch in all_chunks.chunks(batch_size) {
        // Collect text values from the active slice block
        let text_inputs: Vec<String> = batch.iter().map(|(text, _)| text.clone()).collect();

        let payload = BatchEmbeddingRequest {
            model: args.embedding_model.clone(),
            input: text_inputs,
        };

        // Fire the entire array to Ollama in a single HTTP call
        match http_client.post(embed_url).json(&payload).send().await {
            Ok(res) => {
                if let Ok(body) = res.json::<BatchEmbeddingResponse>().await {
                    // Match the returned vector positions back to their respective metadata anchors
                    for ((chunk_text, source_file), vector) in
                        batch.iter().zip(body.embeddings.into_iter())
                    {
                        vector_db.push(DocumentChunk {
                            text: chunk_text.clone(),
                            vector,
                            source_file: source_file.clone(),
                        });
                        successful_embeddings += 1;
                    }
                } else {
                    eprintln!("Warning: Failed to parse batch embedding response.");
                    failed_embeddings += batch.len();
                }
            }
            Err(e) => {
                eprintln!(
                    "Warning: Batch embedding vector calculation block dropped due to error: {}",
                    e
                );
                failed_embeddings += batch.len();
            }
        }
    }

    println!(
        "Embedding generation complete: {} successful, {} failed",
        successful_embeddings, failed_embeddings
    );

    Ok(vector_db)
}

/// Scans a folder recursively for PDF and EPUB files and generates embeddings for all of them.
///
/// This is the high-level entry point for the embedding pipeline. It:
/// 1. Recursively walks the folder specified in `args.folder`
/// 2. Collects all PDF and EPUB files found
/// 3. Delegates to `generate_embeddings_for_documents` for the actual embedding work
///
/// This function does not check for existing embeddings or detect changes - for
/// incremental updates, use `get_changed_documents` and `remove_deleted_embeddings` instead.
///
/// # Arguments
///
/// * `args` - CLI arguments containing the folder path and embedding configuration
/// * `http_client` - A configured `reqwest::Client` for making HTTP requests
/// * `embed_url` - The Ollama batch embedding API URL (e.g., `"http://localhost:11434/api/embed"`)
///
/// # Returns
///
/// A `Vec<DocumentChunk>` containing all embedded text chunks with their vectors.
///
/// # Errors
///
/// Returns an error if:
/// - The folder cannot be walked
/// - Any document parsing or embedding request fails catastrophically
pub async fn generate_all_embeddings(
    args: &Args,
    http_client: &reqwest::Client,
    embed_url: &str,
) -> Result<Vec<DocumentChunk>> {
    // 1. Recursive Document Crawling - Collect all PDF and EPUB paths first
    println!("Scanning folder recursively: {:?}", args.folder);

    let document_files: Vec<(DocumentType, String)> = WalkDir::new(&args.folder)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter_map(|entry| {
            let path = entry.path().to_path_buf();
            if path.is_file() {
                if let Some(ext) = path.extension().and_then(|s| s.to_str()) {
                    let doc_type = match ext {
                        "pdf" => DocumentType::Pdf(path.clone()),
                        "epub" => DocumentType::Epub(path.clone()),
                        _ => return None,
                    };
                    let file_name = path.file_name().unwrap().to_string_lossy().into_owned();
                    Some((doc_type, file_name))
                } else {
                    None
                }
            } else {
                None
            }
        })
        .collect();

    println!(
        "Found {} document files (PDF + EPUB). Parsing in parallel...",
        document_files.len()
    );

    generate_embeddings_for_documents(args, http_client, embed_url, document_files).await
}
